### ISSUE TITLE
Hyphen handling

### ISSUE THREAD

**Issue by blazeu** [andrewda/valid-github-username#1]
- Username shouldn't start or end with hyphen.
- Username shouldn't have multiple hyphen.

**Comment by andrewda** [comment]
More info here: https://github.com/manu-chroma/username-availability-checker/blob/master/websites.yml#L65-L73

Also see https://github.com/manu-chroma/username-availability-checker/blob/master/tests/test_data.yml#L34-L43

**Comment by kx-chen** [comment]
Claiming this task.

**Comment by jayvdb** [comment]
This issue reserved for Google Code-in task [6210154526670848](https://codein.withgoogle.com/dashboard/tasks/6210154526670848).
