### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by andrewda** [andrewda/valid-github-username#3]
Use Chai and Mocha to create some basic unit tests for this repository. Having some basic tests to ensure the library works as advertised would be very nice to have.

This may be a good place to get you started: https://hackernoon.com/a-crash-course-on-testing-with-node-js-6c7428d3da02. Also look into the documentation of chai and mocha to see what else is possible!

**Comment by kx-chen** [comment]
@andrewda would like to work on this issue.

**Comment by andrewda** [comment]
@kx-chen sounds good, thanks! Just submit a PR when you're done (or have any questions want me to look over it)!

**Comment by kx-chen** [comment]
@andrewda Small problem: it looks like the regex is still missing cases for when the username contains trailing, leading and consecutive hyphens. Should I still add test cases for those? Or should I ignore those cases for now and not write tests for them?

**Comment by andrewda** [comment]
Ignore them for now. Those tests can be added in the PR adding the new
rules.

**Comment by jayvdb** [comment]
This issue reserved for Google Code-in task [6291349323120640](https://codein.withgoogle.com/dashboard/tasks/6291349323120640).
