### ISSUE TITLE
Run tests on Travis CI

### ISSUE THREAD

**Issue by andrewda** [andrewda/valid-github-username#5]
Add a `.travis.yml` file which runs the test script. Make sure to test your Travis CI implementation on your fork by enabling it at https://travis-ci.org. Also add a `test` script in the `package.json` file which runs the mocha script and is called from Travis.

Some documentation that might be helpful:
- https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
- https://mochajs.org/#getting-started

**Comment by jayvdb** [comment]
This issue reserved for Google Code-in task [6716184905908224](https://codein.withgoogle.com/dashboard/tasks/6716184905908224).
